### ISSUE TITLE
IInputMapping and Handling Input for Characters

### ISSUE THREAD

**Issue by swangboy55** [swangboy55/3DEngine#12]
There are two parts to this: first is the input mapping and second is handling input for a character.
InputMapping:
InputMapping is a class which contains a set of input and output codes which will be used within the AbstractInputSystem class to load a set of bindings. The idea of this is to have a class which can easily set up these bindings for the programmer, such that when they need to set an input system's bindings, they just give it the InputMapping. The input mapping class will have to be extremely simple, and at some point should be able to load input mappings from some kind of config file. Please ask me about this one before you do it, as I have provided some pretty bad specs for it.

Input for Character:
The input mapping for character will be a set of output codes from the AbstractInputSystem class. These codes will describe certain actions which they will do, such as moving forward, back, left, right, jumping, etc.
My idea for this is that the character class has a set of booleans (or maybe a flag variable?) which can be accessed in a novel and simple way. This will be used by the movement states so that they can properly apply the movements to the character.

**Comment by swangboy55** [comment]
If fiexed  it al gusis dont tttttt


\

**Comment by swangboy55** [comment]
jo wus herrr

**Comment by f16falcona46** [comment]
Should this issue be considered closed?

**Comment by swangboy55** [comment]
No, it has not been implemented to any extent whatsoever.

**Comment by swangboy55** [comment]
Ignore Joe's comments

**Comment by JoeCleary** [comment]
I am interested.
