### ISSUE TITLE
Collision correction system allows fast-moving objects to pass through eachother

### ISSUE THREAD

**Issue by swangboy55** [swangboy55/3DEngine#15]
Initial collision detection for moving objects (see CollisionMesh) properly detects a collision irregardless of the velocity of the two objects. The issue occurs when the collisions are resolved. 
In World.cpp `void World::resolveCollisions(INT32 iterations)` (lines 177-199) the preCorrectionCheck, which checks for overlaps rather than collisions, causes any positional correction to occur. 
This image demonstrates it in 2D:
![demonstration](https://puu.sh/vyh4e/8581bf5991.png)

Possible solutions

1. Only on the first correctional iteration, force the two objects to be overlapping, (use contact points calculated from CollisionMesh?)
2. Change the preCorrectionCheck to use standard collision detection rather than overlap tests.

**Comment by swangboy55** [comment]
Note: this issue only crops up for objects which move fast enough to pass through eachother in a single frame. Assuming the game is running 60tick, it moves objects 1/60th its velocity per second. That means the engine won't resolve tiny collisions (such as quickly clipping the edge of a prism).

**Comment by JoeCleary** [comment]
arpad fix

**Comment by swangboy55** [comment]
arpad fix
