### ISSUE TITLE
Extremely high coefficient of friction causes oddities

### ISSUE THREAD

**Issue by swangboy55** [swangboy55/3DEngine#2]
test this on a wide tilted surface, and drop a small cube on it. In my case, I used two entities: one static and one dynamic, here's the code for the JNA project:

`entities.add(nst.createAddEntity(0, 0, 0, 0.1f, 0, 0, 0, 0, 0, 100, 1.f, 100f, 0, 0, 1, 100));
 entities.add(nst.createAddEntity(0, 7, 0, 0, 0, 0, 0, 0, 0, 1.f, 1.f, 1.f, 0, 1, 1f, 100));`

the coefficent of friction (the last parameter) between two objects is very high, which instantly stops most objects. In this specific case, the large 100x1x100 surface we drop the cube on is tilted along the x axis at 0.1 radians (so it's facing upwards for the smaller cube). Intuitively the small cube would almost not move at all (maybe inch its way down the surface), but for some reason, it climbs up the cube very, very slowly. I've tested this with higher COE's (such as 1000), and that launches the smaller cube down the surface extremely fast, having the opposite effect here. I'm asking someone here to find the issue with high COE values and fix them. 
The code for friction is located in Collision.h within the function `Collision::applyFriction`.
My best assumption for what's causing this has to do with this snippet of code:
`if (glm::length(pVec) < glm::length(frictVector))
{
     frictVector = -pVec;
}`
as well as the code which handles friction for the opposite object

**Comment by daKilla133** [comment]
fixed :~)
