### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by swangboy55** [swangboy55/3DEngine#9]
Components are a nice extension to the Entity class, as they allow for something this project has a big issue with -- extensibility.
Component will be an abstract class which will contain a list of c#-esque event functions (onTick, onResolve, onRender, throwing ideas out there) which will all be called when an entity encounters specific points in its lifetime. Requirements of this task:
- Create a component interface, a list of them will be stored in the entity class
- The entity class will call corresponding component functions for all of its components at certain points (such as: when an entity's tick function is called, it calls all of its components have their onTick function called with necessary arguments passed)
- The component class will contain a pointer to the entity which contains it
- When an entity is destroyed, all of its components are destroyed

This topic is open to much discussion, if you are interested in adding to the extensibility of this project, put a message in the skype group and we will work out a more concrete design for this.

**Comment by ReewassSquared** [comment]
I could help with this.

**Comment by swangboy55** [comment]
Completed base component class

**Comment by f16falcona46** [comment]
Should we have a virtual destructor for Component (to allow Entity to destroy them when it's time to)

**Comment by swangboy55** [comment]
Yes, I will add that in

**Comment by swangboy55** [comment]
Added in virtual destructor, further implementation of this issue is on hiatus as of commit 86558a378b32cdabb0550517967d16dc18e876a7. Whether or not it will be continued now or later is to be decided.

**Comment by swangboy55** [comment]
The component class will first begin implementation once the rendering code is completed. The renderable (within the core project) will be the first subclass of component. PhysicsObject will later be repurposed into a component.

**Comment by swangboy55** [comment]
The (Previously IRenderable) class has now been refactored into its component form (now IRenderComponent).
The only class which needs to be turned into a component now is the PhysicsObject.
